node {
  name = "emqx@127.0.0.1"
  cookie = "gnss_emqx_cookie"
  data_dir = "/opt/emqx/data"
}

dashboard {
  default_username = "admin"
  default_password = "public123"
  token_expired_time = "60m"
  cors = false

  listeners.http {
    bind = "0.0.0.0:18083"
    num_acceptors = 8
    max_connections = 512
    backlog = 1024
    send_timeout = "10s"
    inet6 = false
    ipv6_v6only = false
    proxy_header = false
  }
}

authentication = [
  {
    mechanism = password_based
    backend = http
    method = post
    url = "http://192.168.100.219:3000/api/mqtt/auth"
    body {
      clientid = "${clientid}"
      username = "${username}"
      password = "${password}"
    }
    headers {
      "X-Request-Source" = "EMQX"
      "Content-Type" = "application/json"
    }
  }
]

authorization {
  no_match = allow
  deny_action = ignore
}
