export enum ErrorCode {
  // Validation errors (400)
  INVALID_INPUT = 'INVALID_INPUT',
  MISSING_REQUIRED_FIELD = 'MISSING_REQUIRED_FIELD',

  // Authentication errors (401)
  UNAUTHORIZED = 'UNAUTHORIZED',
  INVALID_CREDENTIALS = 'INVALID_CREDENTIALS',
  SESSION_EXPIRED = 'SESSION_EXPIRED',

  // Authorization errors (403)
  FORBIDDEN = 'FORBIDDEN',
  INSUFFICIENT_PERMISSIONS = 'INSUFFICIENT_PERMISSIONS',

  // Not found errors (404)
  RESOURCE_NOT_FOUND = 'RESOURCE_NOT_FOUND',
  USER_NOT_FOUND = 'USER_NOT_FOUND',

  // Conflict errors (409)
  RESOURCE_ALREADY_EXISTS = 'RESOURCE_ALREADY_EXISTS',
  DUPLICATE_ENTRY = 'DUPLICATE_ENTRY',

  // Too many requests (429)
  TOO_MANY_REQUESTS = 'TOO_MANY_REQUESTS',

  // Server errors (500)
  INTERNAL_SERVER_ERROR = 'INTERNAL_SERVER_ERROR',


  // Conflict errors (409)

  FAILED_TO_SEND_OTP = 'FAILED_TO_SEND_OTP',
  REGISTRATION_FAILED = 'REGISTRATION_FAILED',

  EMAIL_ALREADY_EXISTS = 'EMAIL_ALREADY_EXISTS',
  PENDING_REGISTRATION_EXISTS = 'PENDING_REGISTRATION_EXISTS',

  INVALID_OTP = 'INVALID_OTP',
  EXPIRED_OTP = 'EXPIRED_OTP',
  OTP_ATTEMPTS_EXCEEDED = 'OTP_ATTEMPTS_EXCEEDED',
  REGISTRATION_SESSION_EXPIRED = 'REGISTRATION_SESSION_EXPIRED',

  ADMIN_ALREADY_EXISTS = 'ADMIN_ALREADY_EXISTS',

  VERIFICATION_FAILED = 'VERIFICATION_FAILED',

  DEVICE_GROUP_NOT_FOUND = 'DEVICE_GROUP_NOT_FOUND',
}