[SERVICE]
    Flush        1
    Daemon       Off
    Log_Level    info
    Parsers_File parsers.conf

[INPUT]
    Name          kafka
    Brokers       redpanda:29092
    Topics        app-logs
    Group_Id      fluent-bit-indexer
    Tag           processed.logs

[FILTER]
    Name         parser
    Match        processed.logs
    Key_Name     payload
    Parser       json
    Reserve_Data On

[OUTPUT]
    Name            opensearch
    Match           processed.logs
    Host            opensearch
    Port            9200
    Index           app-logs
    Type            _doc
    Suppress_Type_Name On
    HTTP_User       ${OPENSEARCH_ADMIN_USER}
    HTTP_Passwd     ${OPENSEARCH_ADMIN_PASSWORD}
    tls             On
    tls.verify      Off
    Trace_Output    Off
    Trace_Error     On
