[SERVICE]
    Flush        1
    Daemon       Off
    Log_Level    info
    Parsers_File parsers.conf

[INPUT]
    Name             tail
    Path             /app/logs/*.json
    Parser           json
    Tag              app.logs
    Refresh_Interval 1

[OUTPUT]
    Name        kafka
    Match       app.logs
    Brokers     redpanda:29092
    Topics      app-logs
    rdkafka.queue.buffering.max.ms 1
